### ISSUE TITLE
Remove proprietary, unlicensable engines from list

### ISSUE THREAD

**Issue by Nolram12345** [stevinz/awesome-game-engine-dev#7]
This is mainly about Frostbite and Snowdrop. Neither of these can be licensed and they are entirely proprietary, so they should probably be removed from the list seeing as neither of them are of any use to anyone outside Ubisoft and EA.

**Comment by stevinz** [comment]
I get where you're coming from. Frostbite and Snowdrop are pretty exclusive to Ubisoft and EA, so it makes sense they might not be all that useful for the broader community.

They were included in the AAA category mainly for research purposes as they have played significant roles in the game development industry and can provide insights into game engine design and architecture.

I'll take a closer look at those listings and if it seems like they're not adding much value for folks outside those companies, I'll go ahead and remove them from the list.

Thanks for bringing this to my attention.

**Comment by stevinz** [comment]
You're right, linking directly to EA and Ubisoft's research divisions makes more sense. And Activision's got a solid track record with their presentations, so they'll definitely be a great fit.

I'll go ahead and remove Frostbite and Snowdrop from the "AAA" category and create a new section for these research divisions, i'm thinking "Learning -> Engine Development -> Commercial Studios Research Divisions". Thanks for the suggestion, it feels like a good improvement to the list.

**Comment by Nolram12345** [comment]
Awesome, thanks!
